### ISSUE TITLE
IP address generator

### ISSUE THREAD

**Issue by credibledoc** [credibledoc/credible-doc#10]

**Comment by credibledoc** [comment]
Please create a new method for generation of random IP addresses in the Hint class.
Branch feature/10_ip_address_generator

Thank you.

**Comment by OlgaSemenko** [comment]
Method is created.  @KyryloSemenko

**Comment by OlgaSemenko** [comment]
Last edits completed. @KyryloSemenko

**Comment by KyryloSemenko** [comment]
Thank you.
